# Generated by Django 4.1.7 on 2023-03-19 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_remove_item_item_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
