# Generated by Django 4.1.7 on 2023-03-19 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='current_bid',
            field=models.FloatField(default=0, max_length=100),
        ),
    ]
