# Generated by Django 4.1.7 on 2023-03-19 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_item_current_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='current_bid',
        ),
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.CharField(default='True', max_length=5),
            preserve_default=False,
        ),
    ]
