# Generated by Django 4.1.7 on 2023-03-19 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_item_current_bid_alter_item_starting_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='current_bid',
            field=models.CharField(default=0.0, max_length=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='starting_bid',
            field=models.CharField(max_length=10),
        ),
    ]
