# Generated by Django 4.1.7 on 2023-03-21 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_bid_date_comment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='current_bid_user_id',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
