# Generated by Django 4.1.7 on 2023-03-21 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_item_current_bid_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='title',
            field=models.CharField(default='sunglass', max_length=100),
            preserve_default=False,
        ),
    ]
